name: Build & Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache PHP dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Cache Node (npm) dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Dependencies
        run: npm install
      - name: Build Site
        run: npm run production
      - name: Create CNAME File
        run: echo "docs.slashdotlabsprojects.com" >> build_production/CNAME
      - name: Stage Files
        run: git add -f build_production
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Build for deploy"
      - name: Publish
        run: |
          git subtree split --prefix build_production -b gh-pages
          git push -f origin gh-pages:gh-pages
          git branch -D gh-pages